### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.seq2seq' has no attribute 'prepare_attention'

### ISSUE THREAD

**Issue by blindfish** [Currie32/Chatbot-from-Movie-Dialogue#7]
This part of the code:

```
# Create the training and inference logits
train_logits, inference_logits = seq2seq_model(
    tf.reverse(input_data, [-1]), targets, keep_prob, batch_size, sequence_length, len(answers_vocab_to_int), 
    len(questions_vocab_to_int), encoding_embedding_size, decoding_embedding_size, rnn_size, num_layers, 
    questions_vocab_to_int)

```

Fails with the following error. Anyone get the code to work with TF 1.2.1 or 1.3?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-42-5eb2c4ab2c25> in <module>()
     15     tf.reverse(input_data, [-1]), targets, keep_prob, batch_size, sequence_length, len(answers_vocab_to_int),
     16     len(questions_vocab_to_int), encoding_embedding_size, decoding_embedding_size, rnn_size, num_layers,
---> 17     questions_vocab_to_int)
     18 
     19 # Create a tensor for the inference logits, needed if loading a checkpoint version of the model

<ipython-input-39-bbac5bbc5884> in seq2seq_model(input_data, target_data, keep_prob, batch_size, sequence_length, answers_vocab_size, questions_vocab_size, enc_embedding_size, dec_embedding_size, rnn_size, num_layers, questions_vocab_to_int)
     24                                                 questions_vocab_to_int,
     25                                                 keep_prob,
---> 26                                                 batch_size)
     27     return train_logits, infer_logits

<ipython-input-38-4c62787c7f16> in decoding_layer(dec_embed_input, dec_embeddings, encoder_state, vocab_size, sequence_length, rnn_size, num_layers, vocab_to_int, keep_prob, batch_size)
     24                                             output_fn,
     25                                             keep_prob,
---> 26                                             batch_size)
     27         decoding_scope.reuse_variables()
     28         infer_logits = decoding_layer_infer(encoder_state, 

<ipython-input-36-c7b11c624372> in decoding_layer_train(encoder_state, dec_cell, dec_embed_input, sequence_length, decoding_scope, output_fn, keep_prob, batch_size)
      5     attention_states = tf.zeros([batch_size, 1, dec_cell.output_size])
      6 
----> 7     att_keys, att_vals, att_score_fn, att_construct_fn =             tf.contrib.seq2seq.prepare_attention(attention_states,
      8                                                  attention_option="bahdanau",
      9                                                  num_units=dec_cell.output_size)

AttributeError: module 'tensorflow.contrib.seq2seq' has no attribute 'prepare_attention'
```

**Comment by shreyneil** [comment]
Use tensorflow version 1.0.0, it will only work with that.

**Comment by abhibisht89** [comment]
I am also having the same issue, do I need to downgrade(as i am having tf version '1.3.0') the tf version? or there is some other solution to this issue?

**Comment by Khanquer17** [comment]
same issue

**Comment by shreyneil** [comment]
You have to downgrade, as downgrading worked for me.

**Comment by saurabhrathor** [comment]
Could not find tensorflow version 1.0

C:\Users\eratsau>pip install tensorflow==1.0
Collecting tensorflow==1.0
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement tensorflow==1.0 (from
versions: 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0,
 1.4.0rc1, 1.4.0, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.6.0rc0)
No matching distribution found for tensorflow==1.0

**Comment by adithyaChander** [comment]
Use Python version = 3.5. (Upgrade/downgrade python version accordingly)
Then downgrade tensorflow version to 1.0.0.
This should work :)

**Comment by sumanthd17** [comment]
what is the alternative for tf.contrib.seq2seq.prepare_attention() in the tensorflow API 1.8

**Comment by rahulv1993** [comment]
I am unable to downgrade tensorflow 1.9 to 1.0 on anaconda.
Tried many ways.
please help me with this, thanks!

**Comment by Shanunicorn** [comment]
is there any other way to clear this issue without downgrading the version of tensorflow

**Comment by Shanunicorn** [comment]
@Currie32 @shreyneil @adithyaChander 
does it take more time run this particular cell. 
It takes more than a hour for me to run this.
i am using 4 GB RAM, ubuntu 16.04 , and tensorflow  version 1.0.0

 display_step = 100 # Check training loss after every 100 batches
stop_early = 0 
stop = 5 # If the validation loss does decrease in 5 consecutive checks, stop training
validation_check = ((len(train_questions))//batch_size//2)-1 # Modulus for checking validation loss
total_train_loss = 0 # Record the training loss for each display step
summary_valid_loss = [] # Record the validation loss for saving improvements in the model

checkpoint = "best_model.ckpt" 

sess.run(tf.global_variables_initializer())

for epoch_i in range(1, epochs+1):
    for batch_i, (questions_batch, answers_batch) in enumerate(
            batch_data(train_questions, train_answers, batch_size)):
        start_time = time.time()
        _, loss = sess.run(
            [train_op, cost],
            {input_data: questions_batch,
             targets: answers_batch,
             lr: learning_rate,
             sequence_length: answers_batch.shape[1],
             keep_prob: keep_probability})

        total_train_loss += loss
        end_time = time.time()
        batch_time = end_time - start_time

        if batch_i % display_step == 0:
            print('Epoch {:>3}/{} Batch {:>4}/{} - Loss: {:>6.3f}, Seconds: {:>4.2f}'
                  .format(epoch_i,
                          epochs, 
                          batch_i, 
                          len(train_questions) // batch_size, 
                          total_train_loss / display_step, 
                          batch_time*display_step))
            total_train_loss = 0

        if batch_i % validation_check == 0 and batch_i > 0:
            total_valid_loss = 0
            start_time = time.time()
            for batch_ii, (questions_batch, answers_batch) in \
                    enumerate(batch_data(valid_questions, valid_answers, batch_size)):
                valid_loss = sess.run(
                cost, {input_data: questions_batch,
                       targets: answers_batch,
                       lr: learning_rate,
                       sequence_length: answers_batch.shape[1],
                       keep_prob: 1})
                total_valid_loss += valid_loss
            end_time = time.time()
            batch_time = end_time - start_time
            avg_valid_loss = total_valid_loss / (len(valid_questions) / batch_size)
            print('Valid Loss: {:>6.3f}, Seconds: {:>5.2f}'.format(avg_valid_loss, batch_time))
            
            # Reduce learning rate, but not below its minimum value
            learning_rate *= learning_rate_decay
            if learning_rate < min_learning_rate:
                learning_rate = min_learning_rate

            summary_valid_loss.append(avg_valid_loss)
            if avg_valid_loss <= min(summary_valid_loss):
                print('New Record!') 
                stop_early = 0
                saver = tf.train.Saver() 
                saver.save(sess, checkpoint)

            else:
                print("No Improvement.")
                stop_early += 1
                if stop_early == stop:
                    break
    
    if stop_early == stop:
        print("Stopping Training.")
        break

**Comment by Joshsnailz** [comment]
Is there any other workaround without having to downgrade my tensorflow

**Comment by Swaminathan-R** [comment]
Is there any other workaround other than downgrading TensorFlow?

**Comment by RamKumar-T-R** [comment]
What is the alternative for tensorflow.contrib.seq2seq.prepare_attention() in tensorflow 1.13 or 1.14
